<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BernhardWebstudio\PipefySDK\PHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Pipefy API
 *
 * This is Database's API documentation.  [Here](http://docs.pipefy.apiary.io) you will find the guidelines for getting started with the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BernhardWebstudio\PipefySDK\PHP;

use BernhardWebstudio\PipefySDK\PHP\Configuration;
use BernhardWebstudio\PipefySDK\PHP\ApiException;
use BernhardWebstudio\PipefySDK\PHP\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  BernhardWebstudio\PipefySDK\PHP
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteTableRecordInputParams
     *
     * deleteTableRecord(input: params).
     *
     */
    public function testDeleteTableRecordInputParams()
    {
    }
}
