name: Generate SDK

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 3 * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Swagger
        run: "brew install swagger-codegen"

      - name: Install npx
        run: "npm i -g npx || echo 'Already installed'"
      
      - name: Install yarn dependencies
        run: "yarn install"
      
      - name: Fetch API specs
        run: "yarn graphdoc -e https://api.pipefy.com/graphql -x \"Authorization: Bearer ${{ secrets.GRAPHQL_TOKEN }}\" -p graphdoc-schema-json-plugin -o ./doc/schema"
        # run: "bash ./bin/generateSDK.sh"

      - name: Generate API
        run: "php bin/generatePhpApi.php"

      - name: "Commit Changes"
        uses: EndBug/add-and-commit@v6 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          add: 'src'

          # The message for the commit
          message: 'Commit from GitHub Actions: (Re)Generate'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true

          # Token to use for pushing the commit. The default value won't trigger any workflows, you need to use a Personal Access Token for that.
          # Default: secrets.GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}
