name: Security Check

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 1 * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Swagger
        run: "brew install swagger-codegen"

      - name: Install npx
        uses: "npm i -g npx"
      
      - name: "Run Generation"
        run: "./bin/generateSDK.sh"

      - name: "Commit Changes"
        uses: EndBug/add-and-commit@v6 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          add: 'src'

          # The message for the commit
          message: 'Commit from GitHub Actions: (Re)Generate'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true

          # Token to use for pushing the commit. The default value won't trigger any workflows, you need to use a Personal Access Token for that.
          # Default: secrets.GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}
